package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1



/**
 * AuditTrail generated by hbm2java
 */
public class AuditTrail  implements java.io.Serializable {


     private AuditTrailId id;

    public AuditTrail() {
    }

    public AuditTrail(AuditTrailId id) {
       this.id = id;
    }
   
    public AuditTrailId getId() {
        return this.id;
    }
    
    public void setId(AuditTrailId id) {
        this.id = id;
    }




}


