package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1



/**
 * AuditTrail2 generated by hbm2java
 */
public class AuditTrail2  implements java.io.Serializable {


     private AuditTrail2Id id;

    public AuditTrail2() {
    }

    public AuditTrail2(AuditTrail2Id id) {
       this.id = id;
    }
   
    public AuditTrail2Id getId() {
        return this.id;
    }
    
    public void setId(AuditTrail2Id id) {
        this.id = id;
    }




}


