package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * AudSesiones generated by hbm2java
 */
public class AudSesiones  implements java.io.Serializable {


     private int idAudsesion;
     private Integer idUsuario;
     private Serializable ip;
     private String nombreEquipo;
     private Date fechaRegistro;
     private Character estado;
     private String descripcion;

    public AudSesiones() {
    }

	
    public AudSesiones(int idAudsesion) {
        this.idAudsesion = idAudsesion;
    }
    public AudSesiones(int idAudsesion, Integer idUsuario, Serializable ip, String nombreEquipo, Date fechaRegistro, Character estado, String descripcion) {
       this.idAudsesion = idAudsesion;
       this.idUsuario = idUsuario;
       this.ip = ip;
       this.nombreEquipo = nombreEquipo;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
       this.descripcion = descripcion;
    }
   
    public int getIdAudsesion() {
        return this.idAudsesion;
    }
    
    public void setIdAudsesion(int idAudsesion) {
        this.idAudsesion = idAudsesion;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Serializable getIp() {
        return this.ip;
    }
    
    public void setIp(Serializable ip) {
        this.ip = ip;
    }
    public String getNombreEquipo() {
        return this.nombreEquipo;
    }
    
    public void setNombreEquipo(String nombreEquipo) {
        this.nombreEquipo = nombreEquipo;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


