package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LcArticulo generated by hbm2java
 */
public class LcArticulo  implements java.io.Serializable {


     private int idArticulo;
     private LcDatosDeudores lcDatosDeudores;
     private Integer idCliente;
     private String referencia;
     private String nombreArticulo;
     private Integer tipoCredito;
     private BigDecimal valorArticulo;
     private BigDecimal interes;
     private Integer numCuotas;
     private Integer numCuotasPagadas;
     private Integer numCuotasPendientes;
     private BigDecimal interesMora;
     private BigDecimal gastosAdicional;
     private Date fechaCompra;
     private Date fechaRegistro;
     private String estado;
     private String descripcionCarga;
     private Set lcCuotases = new HashSet(0);

    public LcArticulo() {
    }

	
    public LcArticulo(int idArticulo) {
        this.idArticulo = idArticulo;
    }
    public LcArticulo(int idArticulo, LcDatosDeudores lcDatosDeudores, Integer idCliente, String referencia, String nombreArticulo, Integer tipoCredito, BigDecimal valorArticulo, BigDecimal interes, Integer numCuotas, Integer numCuotasPagadas, Integer numCuotasPendientes, BigDecimal interesMora, BigDecimal gastosAdicional, Date fechaCompra, Date fechaRegistro, String estado, String descripcionCarga, Set lcCuotases) {
       this.idArticulo = idArticulo;
       this.lcDatosDeudores = lcDatosDeudores;
       this.idCliente = idCliente;
       this.referencia = referencia;
       this.nombreArticulo = nombreArticulo;
       this.tipoCredito = tipoCredito;
       this.valorArticulo = valorArticulo;
       this.interes = interes;
       this.numCuotas = numCuotas;
       this.numCuotasPagadas = numCuotasPagadas;
       this.numCuotasPendientes = numCuotasPendientes;
       this.interesMora = interesMora;
       this.gastosAdicional = gastosAdicional;
       this.fechaCompra = fechaCompra;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
       this.descripcionCarga = descripcionCarga;
       this.lcCuotases = lcCuotases;
    }
   
    public int getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(int idArticulo) {
        this.idArticulo = idArticulo;
    }
    public LcDatosDeudores getLcDatosDeudores() {
        return this.lcDatosDeudores;
    }
    
    public void setLcDatosDeudores(LcDatosDeudores lcDatosDeudores) {
        this.lcDatosDeudores = lcDatosDeudores;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getNombreArticulo() {
        return this.nombreArticulo;
    }
    
    public void setNombreArticulo(String nombreArticulo) {
        this.nombreArticulo = nombreArticulo;
    }
    public Integer getTipoCredito() {
        return this.tipoCredito;
    }
    
    public void setTipoCredito(Integer tipoCredito) {
        this.tipoCredito = tipoCredito;
    }
    public BigDecimal getValorArticulo() {
        return this.valorArticulo;
    }
    
    public void setValorArticulo(BigDecimal valorArticulo) {
        this.valorArticulo = valorArticulo;
    }
    public BigDecimal getInteres() {
        return this.interes;
    }
    
    public void setInteres(BigDecimal interes) {
        this.interes = interes;
    }
    public Integer getNumCuotas() {
        return this.numCuotas;
    }
    
    public void setNumCuotas(Integer numCuotas) {
        this.numCuotas = numCuotas;
    }
    public Integer getNumCuotasPagadas() {
        return this.numCuotasPagadas;
    }
    
    public void setNumCuotasPagadas(Integer numCuotasPagadas) {
        this.numCuotasPagadas = numCuotasPagadas;
    }
    public Integer getNumCuotasPendientes() {
        return this.numCuotasPendientes;
    }
    
    public void setNumCuotasPendientes(Integer numCuotasPendientes) {
        this.numCuotasPendientes = numCuotasPendientes;
    }
    public BigDecimal getInteresMora() {
        return this.interesMora;
    }
    
    public void setInteresMora(BigDecimal interesMora) {
        this.interesMora = interesMora;
    }
    public BigDecimal getGastosAdicional() {
        return this.gastosAdicional;
    }
    
    public void setGastosAdicional(BigDecimal gastosAdicional) {
        this.gastosAdicional = gastosAdicional;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getDescripcionCarga() {
        return this.descripcionCarga;
    }
    
    public void setDescripcionCarga(String descripcionCarga) {
        this.descripcionCarga = descripcionCarga;
    }
    public Set getLcCuotases() {
        return this.lcCuotases;
    }
    
    public void setLcCuotases(Set lcCuotases) {
        this.lcCuotases = lcCuotases;
    }




}


