package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1



/**
 * LcAsignacioPiccaTmp generated by hbm2java
 */
public class LcAsignacioPiccaTmp  implements java.io.Serializable {


     private LcAsignacioPiccaTmpId id;

    public LcAsignacioPiccaTmp() {
    }

    public LcAsignacioPiccaTmp(LcAsignacioPiccaTmpId id) {
       this.id = id;
    }
   
    public LcAsignacioPiccaTmpId getId() {
        return this.id;
    }
    
    public void setId(LcAsignacioPiccaTmpId id) {
        this.id = id;
    }




}


