package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LcAsignacionTransTmp generated by hbm2java
 */
public class LcAsignacionTransTmp  implements java.io.Serializable {


     private int idAsig;
     private Integer idSecuencial;
     private Integer idTransaccion;
     private Integer idDeudor;
     private Integer idCliente;
     private Integer idEmpleado;
     private BigDecimal totalVencidos;
     private String estatus;

    public LcAsignacionTransTmp() {
    }

	
    public LcAsignacionTransTmp(int idAsig) {
        this.idAsig = idAsig;
    }
    public LcAsignacionTransTmp(int idAsig, Integer idSecuencial, Integer idTransaccion, Integer idDeudor, Integer idCliente, Integer idEmpleado, BigDecimal totalVencidos, String estatus) {
       this.idAsig = idAsig;
       this.idSecuencial = idSecuencial;
       this.idTransaccion = idTransaccion;
       this.idDeudor = idDeudor;
       this.idCliente = idCliente;
       this.idEmpleado = idEmpleado;
       this.totalVencidos = totalVencidos;
       this.estatus = estatus;
    }
   
    public int getIdAsig() {
        return this.idAsig;
    }
    
    public void setIdAsig(int idAsig) {
        this.idAsig = idAsig;
    }
    public Integer getIdSecuencial() {
        return this.idSecuencial;
    }
    
    public void setIdSecuencial(Integer idSecuencial) {
        this.idSecuencial = idSecuencial;
    }
    public Integer getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(Integer idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public Integer getIdDeudor() {
        return this.idDeudor;
    }
    
    public void setIdDeudor(Integer idDeudor) {
        this.idDeudor = idDeudor;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public BigDecimal getTotalVencidos() {
        return this.totalVencidos;
    }
    
    public void setTotalVencidos(BigDecimal totalVencidos) {
        this.totalVencidos = totalVencidos;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }




}


