package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1



/**
 * LcCiudades2 generated by hbm2java
 */
public class LcCiudades2  implements java.io.Serializable {


     private LcCiudades2Id id;

    public LcCiudades2() {
    }

    public LcCiudades2(LcCiudades2Id id) {
       this.id = id;
    }
   
    public LcCiudades2Id getId() {
        return this.id;
    }
    
    public void setId(LcCiudades2Id id) {
        this.id = id;
    }




}


