package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1



/**
 * LcCiudades2Id generated by hbm2java
 */
public class LcCiudades2Id  implements java.io.Serializable {


     private Integer idCiudad;
     private Integer idProvincia;
     private String ciudad;
     private String estado;

    public LcCiudades2Id() {
    }

    public LcCiudades2Id(Integer idCiudad, Integer idProvincia, String ciudad, String estado) {
       this.idCiudad = idCiudad;
       this.idProvincia = idProvincia;
       this.ciudad = ciudad;
       this.estado = estado;
    }
   
    public Integer getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(Integer idCiudad) {
        this.idCiudad = idCiudad;
    }
    public Integer getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(Integer idProvincia) {
        this.idProvincia = idProvincia;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LcCiudades2Id) ) return false;
		 LcCiudades2Id castOther = ( LcCiudades2Id ) other; 
         
		 return ( (this.getIdCiudad()==castOther.getIdCiudad()) || ( this.getIdCiudad()!=null && castOther.getIdCiudad()!=null && this.getIdCiudad().equals(castOther.getIdCiudad()) ) )
 && ( (this.getIdProvincia()==castOther.getIdProvincia()) || ( this.getIdProvincia()!=null && castOther.getIdProvincia()!=null && this.getIdProvincia().equals(castOther.getIdProvincia()) ) )
 && ( (this.getCiudad()==castOther.getCiudad()) || ( this.getCiudad()!=null && castOther.getCiudad()!=null && this.getCiudad().equals(castOther.getCiudad()) ) )
 && ( (this.getEstado()==castOther.getEstado()) || ( this.getEstado()!=null && castOther.getEstado()!=null && this.getEstado().equals(castOther.getEstado()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdCiudad() == null ? 0 : this.getIdCiudad().hashCode() );
         result = 37 * result + ( getIdProvincia() == null ? 0 : this.getIdProvincia().hashCode() );
         result = 37 * result + ( getCiudad() == null ? 0 : this.getCiudad().hashCode() );
         result = 37 * result + ( getEstado() == null ? 0 : this.getEstado().hashCode() );
         return result;
   }   


}


