package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LcDetCampanias generated by hbm2java
 */
public class LcDetCampanias  implements java.io.Serializable {


     private int idDetCampanias;
     private LcClientes lcClientes;
     private LcDatosDeudores lcDatosDeudores;
     private LcEmpleados lcEmpleados;
     private Integer idCampanias;
     private Integer idCartera;
     private Integer idSubCartera;
     private Integer idSegmento;
     private Integer idSubSegmento;
     private String identificacion;
     private String nombresCompleto;
     private Integer diasMora;
     private BigDecimal totalVencidos;
     private BigDecimal pagos;
     private Date fechaUltPagos;
     private BigDecimal saldo;
     private BigDecimal valorCompro;
     private Date fechaComp;
     private Date fechUltimaGestion;
     private String ultimaGestion;
     private String resultadoGestion;
     private String estado;
     private Date fechaDesde;
     private Date fecha1Hasta;
     private String asignacion;

    public LcDetCampanias() {
    }

	
    public LcDetCampanias(int idDetCampanias) {
        this.idDetCampanias = idDetCampanias;
    }
    public LcDetCampanias(int idDetCampanias, LcClientes lcClientes, LcDatosDeudores lcDatosDeudores, LcEmpleados lcEmpleados, Integer idCampanias, Integer idCartera, Integer idSubCartera, Integer idSegmento, Integer idSubSegmento, String identificacion, String nombresCompleto, Integer diasMora, BigDecimal totalVencidos, BigDecimal pagos, Date fechaUltPagos, BigDecimal saldo, BigDecimal valorCompro, Date fechaComp, Date fechUltimaGestion, String ultimaGestion, String resultadoGestion, String estado, Date fechaDesde, Date fecha1Hasta, String asignacion) {
       this.idDetCampanias = idDetCampanias;
       this.lcClientes = lcClientes;
       this.lcDatosDeudores = lcDatosDeudores;
       this.lcEmpleados = lcEmpleados;
       this.idCampanias = idCampanias;
       this.idCartera = idCartera;
       this.idSubCartera = idSubCartera;
       this.idSegmento = idSegmento;
       this.idSubSegmento = idSubSegmento;
       this.identificacion = identificacion;
       this.nombresCompleto = nombresCompleto;
       this.diasMora = diasMora;
       this.totalVencidos = totalVencidos;
       this.pagos = pagos;
       this.fechaUltPagos = fechaUltPagos;
       this.saldo = saldo;
       this.valorCompro = valorCompro;
       this.fechaComp = fechaComp;
       this.fechUltimaGestion = fechUltimaGestion;
       this.ultimaGestion = ultimaGestion;
       this.resultadoGestion = resultadoGestion;
       this.estado = estado;
       this.fechaDesde = fechaDesde;
       this.fecha1Hasta = fecha1Hasta;
       this.asignacion = asignacion;
    }
   
    public int getIdDetCampanias() {
        return this.idDetCampanias;
    }
    
    public void setIdDetCampanias(int idDetCampanias) {
        this.idDetCampanias = idDetCampanias;
    }
    public LcClientes getLcClientes() {
        return this.lcClientes;
    }
    
    public void setLcClientes(LcClientes lcClientes) {
        this.lcClientes = lcClientes;
    }
    public LcDatosDeudores getLcDatosDeudores() {
        return this.lcDatosDeudores;
    }
    
    public void setLcDatosDeudores(LcDatosDeudores lcDatosDeudores) {
        this.lcDatosDeudores = lcDatosDeudores;
    }
    public LcEmpleados getLcEmpleados() {
        return this.lcEmpleados;
    }
    
    public void setLcEmpleados(LcEmpleados lcEmpleados) {
        this.lcEmpleados = lcEmpleados;
    }
    public Integer getIdCampanias() {
        return this.idCampanias;
    }
    
    public void setIdCampanias(Integer idCampanias) {
        this.idCampanias = idCampanias;
    }
    public Integer getIdCartera() {
        return this.idCartera;
    }
    
    public void setIdCartera(Integer idCartera) {
        this.idCartera = idCartera;
    }
    public Integer getIdSubCartera() {
        return this.idSubCartera;
    }
    
    public void setIdSubCartera(Integer idSubCartera) {
        this.idSubCartera = idSubCartera;
    }
    public Integer getIdSegmento() {
        return this.idSegmento;
    }
    
    public void setIdSegmento(Integer idSegmento) {
        this.idSegmento = idSegmento;
    }
    public Integer getIdSubSegmento() {
        return this.idSubSegmento;
    }
    
    public void setIdSubSegmento(Integer idSubSegmento) {
        this.idSubSegmento = idSubSegmento;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public String getNombresCompleto() {
        return this.nombresCompleto;
    }
    
    public void setNombresCompleto(String nombresCompleto) {
        this.nombresCompleto = nombresCompleto;
    }
    public Integer getDiasMora() {
        return this.diasMora;
    }
    
    public void setDiasMora(Integer diasMora) {
        this.diasMora = diasMora;
    }
    public BigDecimal getTotalVencidos() {
        return this.totalVencidos;
    }
    
    public void setTotalVencidos(BigDecimal totalVencidos) {
        this.totalVencidos = totalVencidos;
    }
    public BigDecimal getPagos() {
        return this.pagos;
    }
    
    public void setPagos(BigDecimal pagos) {
        this.pagos = pagos;
    }
    public Date getFechaUltPagos() {
        return this.fechaUltPagos;
    }
    
    public void setFechaUltPagos(Date fechaUltPagos) {
        this.fechaUltPagos = fechaUltPagos;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    public BigDecimal getValorCompro() {
        return this.valorCompro;
    }
    
    public void setValorCompro(BigDecimal valorCompro) {
        this.valorCompro = valorCompro;
    }
    public Date getFechaComp() {
        return this.fechaComp;
    }
    
    public void setFechaComp(Date fechaComp) {
        this.fechaComp = fechaComp;
    }
    public Date getFechUltimaGestion() {
        return this.fechUltimaGestion;
    }
    
    public void setFechUltimaGestion(Date fechUltimaGestion) {
        this.fechUltimaGestion = fechUltimaGestion;
    }
    public String getUltimaGestion() {
        return this.ultimaGestion;
    }
    
    public void setUltimaGestion(String ultimaGestion) {
        this.ultimaGestion = ultimaGestion;
    }
    public String getResultadoGestion() {
        return this.resultadoGestion;
    }
    
    public void setResultadoGestion(String resultadoGestion) {
        this.resultadoGestion = resultadoGestion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaDesde() {
        return this.fechaDesde;
    }
    
    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }
    public Date getFecha1Hasta() {
        return this.fecha1Hasta;
    }
    
    public void setFecha1Hasta(Date fecha1Hasta) {
        this.fecha1Hasta = fecha1Hasta;
    }
    public String getAsignacion() {
        return this.asignacion;
    }
    
    public void setAsignacion(String asignacion) {
        this.asignacion = asignacion;
    }




}


