package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LcEstadoCivil generated by hbm2java
 */
public class LcEstadoCivil  implements java.io.Serializable {


     private int idEstcivil;
     private String abreviatura;
     private String descripcion;
     private String estado;
     private Set lcEmpleadoses = new HashSet(0);

    public LcEstadoCivil() {
    }

	
    public LcEstadoCivil(int idEstcivil) {
        this.idEstcivil = idEstcivil;
    }
    public LcEstadoCivil(int idEstcivil, String abreviatura, String descripcion, String estado, Set lcEmpleadoses) {
       this.idEstcivil = idEstcivil;
       this.abreviatura = abreviatura;
       this.descripcion = descripcion;
       this.estado = estado;
       this.lcEmpleadoses = lcEmpleadoses;
    }
   
    public int getIdEstcivil() {
        return this.idEstcivil;
    }
    
    public void setIdEstcivil(int idEstcivil) {
        this.idEstcivil = idEstcivil;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getLcEmpleadoses() {
        return this.lcEmpleadoses;
    }
    
    public void setLcEmpleadoses(Set lcEmpleadoses) {
        this.lcEmpleadoses = lcEmpleadoses;
    }




}


