package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LcFormapagoRecaudacion2Id generated by hbm2java
 */
public class LcFormapagoRecaudacion2Id  implements java.io.Serializable {


     private Integer idFormpago;
     private Integer idRecaudacion;
     private Integer tipoFormaPago;
     private BigDecimal totalRecaudado;
     private Integer idEntidadFinanciera;
     private String numCheque;
     private String numTarjetaCred;
     private Date fechaCobro;
     private Date fechaRegistro;
     private Date fechaActualizado;
     private String estado;

    public LcFormapagoRecaudacion2Id() {
    }

    public LcFormapagoRecaudacion2Id(Integer idFormpago, Integer idRecaudacion, Integer tipoFormaPago, BigDecimal totalRecaudado, Integer idEntidadFinanciera, String numCheque, String numTarjetaCred, Date fechaCobro, Date fechaRegistro, Date fechaActualizado, String estado) {
       this.idFormpago = idFormpago;
       this.idRecaudacion = idRecaudacion;
       this.tipoFormaPago = tipoFormaPago;
       this.totalRecaudado = totalRecaudado;
       this.idEntidadFinanciera = idEntidadFinanciera;
       this.numCheque = numCheque;
       this.numTarjetaCred = numTarjetaCred;
       this.fechaCobro = fechaCobro;
       this.fechaRegistro = fechaRegistro;
       this.fechaActualizado = fechaActualizado;
       this.estado = estado;
    }
   
    public Integer getIdFormpago() {
        return this.idFormpago;
    }
    
    public void setIdFormpago(Integer idFormpago) {
        this.idFormpago = idFormpago;
    }
    public Integer getIdRecaudacion() {
        return this.idRecaudacion;
    }
    
    public void setIdRecaudacion(Integer idRecaudacion) {
        this.idRecaudacion = idRecaudacion;
    }
    public Integer getTipoFormaPago() {
        return this.tipoFormaPago;
    }
    
    public void setTipoFormaPago(Integer tipoFormaPago) {
        this.tipoFormaPago = tipoFormaPago;
    }
    public BigDecimal getTotalRecaudado() {
        return this.totalRecaudado;
    }
    
    public void setTotalRecaudado(BigDecimal totalRecaudado) {
        this.totalRecaudado = totalRecaudado;
    }
    public Integer getIdEntidadFinanciera() {
        return this.idEntidadFinanciera;
    }
    
    public void setIdEntidadFinanciera(Integer idEntidadFinanciera) {
        this.idEntidadFinanciera = idEntidadFinanciera;
    }
    public String getNumCheque() {
        return this.numCheque;
    }
    
    public void setNumCheque(String numCheque) {
        this.numCheque = numCheque;
    }
    public String getNumTarjetaCred() {
        return this.numTarjetaCred;
    }
    
    public void setNumTarjetaCred(String numTarjetaCred) {
        this.numTarjetaCred = numTarjetaCred;
    }
    public Date getFechaCobro() {
        return this.fechaCobro;
    }
    
    public void setFechaCobro(Date fechaCobro) {
        this.fechaCobro = fechaCobro;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaActualizado() {
        return this.fechaActualizado;
    }
    
    public void setFechaActualizado(Date fechaActualizado) {
        this.fechaActualizado = fechaActualizado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LcFormapagoRecaudacion2Id) ) return false;
		 LcFormapagoRecaudacion2Id castOther = ( LcFormapagoRecaudacion2Id ) other; 
         
		 return ( (this.getIdFormpago()==castOther.getIdFormpago()) || ( this.getIdFormpago()!=null && castOther.getIdFormpago()!=null && this.getIdFormpago().equals(castOther.getIdFormpago()) ) )
 && ( (this.getIdRecaudacion()==castOther.getIdRecaudacion()) || ( this.getIdRecaudacion()!=null && castOther.getIdRecaudacion()!=null && this.getIdRecaudacion().equals(castOther.getIdRecaudacion()) ) )
 && ( (this.getTipoFormaPago()==castOther.getTipoFormaPago()) || ( this.getTipoFormaPago()!=null && castOther.getTipoFormaPago()!=null && this.getTipoFormaPago().equals(castOther.getTipoFormaPago()) ) )
 && ( (this.getTotalRecaudado()==castOther.getTotalRecaudado()) || ( this.getTotalRecaudado()!=null && castOther.getTotalRecaudado()!=null && this.getTotalRecaudado().equals(castOther.getTotalRecaudado()) ) )
 && ( (this.getIdEntidadFinanciera()==castOther.getIdEntidadFinanciera()) || ( this.getIdEntidadFinanciera()!=null && castOther.getIdEntidadFinanciera()!=null && this.getIdEntidadFinanciera().equals(castOther.getIdEntidadFinanciera()) ) )
 && ( (this.getNumCheque()==castOther.getNumCheque()) || ( this.getNumCheque()!=null && castOther.getNumCheque()!=null && this.getNumCheque().equals(castOther.getNumCheque()) ) )
 && ( (this.getNumTarjetaCred()==castOther.getNumTarjetaCred()) || ( this.getNumTarjetaCred()!=null && castOther.getNumTarjetaCred()!=null && this.getNumTarjetaCred().equals(castOther.getNumTarjetaCred()) ) )
 && ( (this.getFechaCobro()==castOther.getFechaCobro()) || ( this.getFechaCobro()!=null && castOther.getFechaCobro()!=null && this.getFechaCobro().equals(castOther.getFechaCobro()) ) )
 && ( (this.getFechaRegistro()==castOther.getFechaRegistro()) || ( this.getFechaRegistro()!=null && castOther.getFechaRegistro()!=null && this.getFechaRegistro().equals(castOther.getFechaRegistro()) ) )
 && ( (this.getFechaActualizado()==castOther.getFechaActualizado()) || ( this.getFechaActualizado()!=null && castOther.getFechaActualizado()!=null && this.getFechaActualizado().equals(castOther.getFechaActualizado()) ) )
 && ( (this.getEstado()==castOther.getEstado()) || ( this.getEstado()!=null && castOther.getEstado()!=null && this.getEstado().equals(castOther.getEstado()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdFormpago() == null ? 0 : this.getIdFormpago().hashCode() );
         result = 37 * result + ( getIdRecaudacion() == null ? 0 : this.getIdRecaudacion().hashCode() );
         result = 37 * result + ( getTipoFormaPago() == null ? 0 : this.getTipoFormaPago().hashCode() );
         result = 37 * result + ( getTotalRecaudado() == null ? 0 : this.getTotalRecaudado().hashCode() );
         result = 37 * result + ( getIdEntidadFinanciera() == null ? 0 : this.getIdEntidadFinanciera().hashCode() );
         result = 37 * result + ( getNumCheque() == null ? 0 : this.getNumCheque().hashCode() );
         result = 37 * result + ( getNumTarjetaCred() == null ? 0 : this.getNumTarjetaCred().hashCode() );
         result = 37 * result + ( getFechaCobro() == null ? 0 : this.getFechaCobro().hashCode() );
         result = 37 * result + ( getFechaRegistro() == null ? 0 : this.getFechaRegistro().hashCode() );
         result = 37 * result + ( getFechaActualizado() == null ? 0 : this.getFechaActualizado().hashCode() );
         result = 37 * result + ( getEstado() == null ? 0 : this.getEstado().hashCode() );
         return result;
   }   


}


