package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LcFormapagoRecaudacion generated by hbm2java
 */
public class LcFormapagoRecaudacion  implements java.io.Serializable {


     private int idFormpago;
     private LcRecaudaciones lcRecaudaciones;
     private LcTipoFormaPago lcTipoFormaPago;
     private BigDecimal totalRecaudado;
     private Integer idEntidadFinanciera;
     private String numCheque;
     private String numCuenta;
     private String numTarjetaCred;
     private Date fechaCobro;
     private Date fechaRegistro;
     private Date fechaActualizado;
     private String estado;

    public LcFormapagoRecaudacion() {
    }

	
    public LcFormapagoRecaudacion(int idFormpago) {
        this.idFormpago = idFormpago;
    }
    public LcFormapagoRecaudacion(int idFormpago, LcRecaudaciones lcRecaudaciones, LcTipoFormaPago lcTipoFormaPago, BigDecimal totalRecaudado, Integer idEntidadFinanciera, String numCheque, String numCuenta, String numTarjetaCred, Date fechaCobro, Date fechaRegistro, Date fechaActualizado, String estado) {
       this.idFormpago = idFormpago;
       this.lcRecaudaciones = lcRecaudaciones;
       this.lcTipoFormaPago = lcTipoFormaPago;
       this.totalRecaudado = totalRecaudado;
       this.idEntidadFinanciera = idEntidadFinanciera;
       this.numCheque = numCheque;
       this.numCuenta = numCuenta;
       this.numTarjetaCred = numTarjetaCred;
       this.fechaCobro = fechaCobro;
       this.fechaRegistro = fechaRegistro;
       this.fechaActualizado = fechaActualizado;
       this.estado = estado;
    }
   
    public int getIdFormpago() {
        return this.idFormpago;
    }
    
    public void setIdFormpago(int idFormpago) {
        this.idFormpago = idFormpago;
    }
    public LcRecaudaciones getLcRecaudaciones() {
        return this.lcRecaudaciones;
    }
    
    public void setLcRecaudaciones(LcRecaudaciones lcRecaudaciones) {
        this.lcRecaudaciones = lcRecaudaciones;
    }
    public LcTipoFormaPago getLcTipoFormaPago() {
        return this.lcTipoFormaPago;
    }
    
    public void setLcTipoFormaPago(LcTipoFormaPago lcTipoFormaPago) {
        this.lcTipoFormaPago = lcTipoFormaPago;
    }
    public BigDecimal getTotalRecaudado() {
        return this.totalRecaudado;
    }
    
    public void setTotalRecaudado(BigDecimal totalRecaudado) {
        this.totalRecaudado = totalRecaudado;
    }
    public Integer getIdEntidadFinanciera() {
        return this.idEntidadFinanciera;
    }
    
    public void setIdEntidadFinanciera(Integer idEntidadFinanciera) {
        this.idEntidadFinanciera = idEntidadFinanciera;
    }
    public String getNumCheque() {
        return this.numCheque;
    }
    
    public void setNumCheque(String numCheque) {
        this.numCheque = numCheque;
    }
    public String getNumCuenta() {
        return this.numCuenta;
    }
    
    public void setNumCuenta(String numCuenta) {
        this.numCuenta = numCuenta;
    }
    public String getNumTarjetaCred() {
        return this.numTarjetaCred;
    }
    
    public void setNumTarjetaCred(String numTarjetaCred) {
        this.numTarjetaCred = numTarjetaCred;
    }
    public Date getFechaCobro() {
        return this.fechaCobro;
    }
    
    public void setFechaCobro(Date fechaCobro) {
        this.fechaCobro = fechaCobro;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaActualizado() {
        return this.fechaActualizado;
    }
    
    public void setFechaActualizado(Date fechaActualizado) {
        this.fechaActualizado = fechaActualizado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


