package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1



/**
 * LcFormapagoRecaudacion2 generated by hbm2java
 */
public class LcFormapagoRecaudacion2  implements java.io.Serializable {


     private LcFormapagoRecaudacion2Id id;

    public LcFormapagoRecaudacion2() {
    }

    public LcFormapagoRecaudacion2(LcFormapagoRecaudacion2Id id) {
       this.id = id;
    }
   
    public LcFormapagoRecaudacion2Id getId() {
        return this.id;
    }
    
    public void setId(LcFormapagoRecaudacion2Id id) {
        this.id = id;
    }




}


