package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1



/**
 * LcGestionesTmp generated by hbm2java
 */
public class LcGestionesTmp  implements java.io.Serializable {


     private LcGestionesTmpId id;

    public LcGestionesTmp() {
    }

    public LcGestionesTmp(LcGestionesTmpId id) {
       this.id = id;
    }
   
    public LcGestionesTmpId getId() {
        return this.id;
    }
    
    public void setId(LcGestionesTmpId id) {
        this.id = id;
    }




}


