package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1



/**
 * LcGestionesTmp22 generated by hbm2java
 */
public class LcGestionesTmp22  implements java.io.Serializable {


     private LcGestionesTmp22Id id;

    public LcGestionesTmp22() {
    }

    public LcGestionesTmp22(LcGestionesTmp22Id id) {
       this.id = id;
    }
   
    public LcGestionesTmp22Id getId() {
        return this.id;
    }
    
    public void setId(LcGestionesTmp22Id id) {
        this.id = id;
    }




}


