package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1



/**
 * LcGestionesTmp222 generated by hbm2java
 */
public class LcGestionesTmp222  implements java.io.Serializable {


     private LcGestionesTmp222Id id;

    public LcGestionesTmp222() {
    }

    public LcGestionesTmp222(LcGestionesTmp222Id id) {
       this.id = id;
    }
   
    public LcGestionesTmp222Id getId() {
        return this.id;
    }
    
    public void setId(LcGestionesTmp222Id id) {
        this.id = id;
    }




}


