package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcGestionesTmpId generated by hbm2java
 */
public class LcGestionesTmpId  implements java.io.Serializable {


     private String identificacion;
     private Integer idEmpleado;
     private Date fechaTransaccion;
     private Integer idTipoResultado;
     private String observacion;
     private Date fechaCompromiso;

    public LcGestionesTmpId() {
    }

    public LcGestionesTmpId(String identificacion, Integer idEmpleado, Date fechaTransaccion, Integer idTipoResultado, String observacion, Date fechaCompromiso) {
       this.identificacion = identificacion;
       this.idEmpleado = idEmpleado;
       this.fechaTransaccion = fechaTransaccion;
       this.idTipoResultado = idTipoResultado;
       this.observacion = observacion;
       this.fechaCompromiso = fechaCompromiso;
    }
   
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Date getFechaTransaccion() {
        return this.fechaTransaccion;
    }
    
    public void setFechaTransaccion(Date fechaTransaccion) {
        this.fechaTransaccion = fechaTransaccion;
    }
    public Integer getIdTipoResultado() {
        return this.idTipoResultado;
    }
    
    public void setIdTipoResultado(Integer idTipoResultado) {
        this.idTipoResultado = idTipoResultado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaCompromiso() {
        return this.fechaCompromiso;
    }
    
    public void setFechaCompromiso(Date fechaCompromiso) {
        this.fechaCompromiso = fechaCompromiso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LcGestionesTmpId) ) return false;
		 LcGestionesTmpId castOther = ( LcGestionesTmpId ) other; 
         
		 return ( (this.getIdentificacion()==castOther.getIdentificacion()) || ( this.getIdentificacion()!=null && castOther.getIdentificacion()!=null && this.getIdentificacion().equals(castOther.getIdentificacion()) ) )
 && ( (this.getIdEmpleado()==castOther.getIdEmpleado()) || ( this.getIdEmpleado()!=null && castOther.getIdEmpleado()!=null && this.getIdEmpleado().equals(castOther.getIdEmpleado()) ) )
 && ( (this.getFechaTransaccion()==castOther.getFechaTransaccion()) || ( this.getFechaTransaccion()!=null && castOther.getFechaTransaccion()!=null && this.getFechaTransaccion().equals(castOther.getFechaTransaccion()) ) )
 && ( (this.getIdTipoResultado()==castOther.getIdTipoResultado()) || ( this.getIdTipoResultado()!=null && castOther.getIdTipoResultado()!=null && this.getIdTipoResultado().equals(castOther.getIdTipoResultado()) ) )
 && ( (this.getObservacion()==castOther.getObservacion()) || ( this.getObservacion()!=null && castOther.getObservacion()!=null && this.getObservacion().equals(castOther.getObservacion()) ) )
 && ( (this.getFechaCompromiso()==castOther.getFechaCompromiso()) || ( this.getFechaCompromiso()!=null && castOther.getFechaCompromiso()!=null && this.getFechaCompromiso().equals(castOther.getFechaCompromiso()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdentificacion() == null ? 0 : this.getIdentificacion().hashCode() );
         result = 37 * result + ( getIdEmpleado() == null ? 0 : this.getIdEmpleado().hashCode() );
         result = 37 * result + ( getFechaTransaccion() == null ? 0 : this.getFechaTransaccion().hashCode() );
         result = 37 * result + ( getIdTipoResultado() == null ? 0 : this.getIdTipoResultado().hashCode() );
         result = 37 * result + ( getObservacion() == null ? 0 : this.getObservacion().hashCode() );
         result = 37 * result + ( getFechaCompromiso() == null ? 0 : this.getFechaCompromiso().hashCode() );
         return result;
   }   


}


