package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcGestionesTmp222Id generated by hbm2java
 */
public class LcGestionesTmp222Id  implements java.io.Serializable {


     private Integer idDeudor;
     private Integer idCliente;
     private Integer idEmpleado;
     private Integer idTipoGestion;
     private Integer idTipoResultado;
     private String observacion;
     private Date fechaTransaccion;
     private String estado;

    public LcGestionesTmp222Id() {
    }

    public LcGestionesTmp222Id(Integer idDeudor, Integer idCliente, Integer idEmpleado, Integer idTipoGestion, Integer idTipoResultado, String observacion, Date fechaTransaccion, String estado) {
       this.idDeudor = idDeudor;
       this.idCliente = idCliente;
       this.idEmpleado = idEmpleado;
       this.idTipoGestion = idTipoGestion;
       this.idTipoResultado = idTipoResultado;
       this.observacion = observacion;
       this.fechaTransaccion = fechaTransaccion;
       this.estado = estado;
    }
   
    public Integer getIdDeudor() {
        return this.idDeudor;
    }
    
    public void setIdDeudor(Integer idDeudor) {
        this.idDeudor = idDeudor;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Integer getIdTipoGestion() {
        return this.idTipoGestion;
    }
    
    public void setIdTipoGestion(Integer idTipoGestion) {
        this.idTipoGestion = idTipoGestion;
    }
    public Integer getIdTipoResultado() {
        return this.idTipoResultado;
    }
    
    public void setIdTipoResultado(Integer idTipoResultado) {
        this.idTipoResultado = idTipoResultado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaTransaccion() {
        return this.fechaTransaccion;
    }
    
    public void setFechaTransaccion(Date fechaTransaccion) {
        this.fechaTransaccion = fechaTransaccion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LcGestionesTmp222Id) ) return false;
		 LcGestionesTmp222Id castOther = ( LcGestionesTmp222Id ) other; 
         
		 return ( (this.getIdDeudor()==castOther.getIdDeudor()) || ( this.getIdDeudor()!=null && castOther.getIdDeudor()!=null && this.getIdDeudor().equals(castOther.getIdDeudor()) ) )
 && ( (this.getIdCliente()==castOther.getIdCliente()) || ( this.getIdCliente()!=null && castOther.getIdCliente()!=null && this.getIdCliente().equals(castOther.getIdCliente()) ) )
 && ( (this.getIdEmpleado()==castOther.getIdEmpleado()) || ( this.getIdEmpleado()!=null && castOther.getIdEmpleado()!=null && this.getIdEmpleado().equals(castOther.getIdEmpleado()) ) )
 && ( (this.getIdTipoGestion()==castOther.getIdTipoGestion()) || ( this.getIdTipoGestion()!=null && castOther.getIdTipoGestion()!=null && this.getIdTipoGestion().equals(castOther.getIdTipoGestion()) ) )
 && ( (this.getIdTipoResultado()==castOther.getIdTipoResultado()) || ( this.getIdTipoResultado()!=null && castOther.getIdTipoResultado()!=null && this.getIdTipoResultado().equals(castOther.getIdTipoResultado()) ) )
 && ( (this.getObservacion()==castOther.getObservacion()) || ( this.getObservacion()!=null && castOther.getObservacion()!=null && this.getObservacion().equals(castOther.getObservacion()) ) )
 && ( (this.getFechaTransaccion()==castOther.getFechaTransaccion()) || ( this.getFechaTransaccion()!=null && castOther.getFechaTransaccion()!=null && this.getFechaTransaccion().equals(castOther.getFechaTransaccion()) ) )
 && ( (this.getEstado()==castOther.getEstado()) || ( this.getEstado()!=null && castOther.getEstado()!=null && this.getEstado().equals(castOther.getEstado()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdDeudor() == null ? 0 : this.getIdDeudor().hashCode() );
         result = 37 * result + ( getIdCliente() == null ? 0 : this.getIdCliente().hashCode() );
         result = 37 * result + ( getIdEmpleado() == null ? 0 : this.getIdEmpleado().hashCode() );
         result = 37 * result + ( getIdTipoGestion() == null ? 0 : this.getIdTipoGestion().hashCode() );
         result = 37 * result + ( getIdTipoResultado() == null ? 0 : this.getIdTipoResultado().hashCode() );
         result = 37 * result + ( getObservacion() == null ? 0 : this.getObservacion().hashCode() );
         result = 37 * result + ( getFechaTransaccion() == null ? 0 : this.getFechaTransaccion().hashCode() );
         result = 37 * result + ( getEstado() == null ? 0 : this.getEstado().hashCode() );
         return result;
   }   


}


