package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcInstitucion generated by hbm2java
 */
public class LcInstitucion  implements java.io.Serializable {


     private int idInstitucion;
     private String nombreInstitucion;
     private String identificacion;
     private Date fechaCreacion;
     private Date fechaActualizacion;
     private String estado;

    public LcInstitucion() {
    }

	
    public LcInstitucion(int idInstitucion) {
        this.idInstitucion = idInstitucion;
    }
    public LcInstitucion(int idInstitucion, String nombreInstitucion, String identificacion, Date fechaCreacion, Date fechaActualizacion, String estado) {
       this.idInstitucion = idInstitucion;
       this.nombreInstitucion = nombreInstitucion;
       this.identificacion = identificacion;
       this.fechaCreacion = fechaCreacion;
       this.fechaActualizacion = fechaActualizacion;
       this.estado = estado;
    }
   
    public int getIdInstitucion() {
        return this.idInstitucion;
    }
    
    public void setIdInstitucion(int idInstitucion) {
        this.idInstitucion = idInstitucion;
    }
    public String getNombreInstitucion() {
        return this.nombreInstitucion;
    }
    
    public void setNombreInstitucion(String nombreInstitucion) {
        this.nombreInstitucion = nombreInstitucion;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


