package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcModuloRol generated by hbm2java
 */
public class LcModuloRol  implements java.io.Serializable {


     private int idModuloRol;
     private LcEmpresa lcEmpresa;
     private LcModulos lcModulos;
     private LcRoles lcRoles;
     private Integer nivelModulo;
     private Integer grupoMod;
     private Date fechaCreacion;
     private String estado;
     private Integer ordenReg;

    public LcModuloRol() {
    }

	
    public LcModuloRol(int idModuloRol) {
        this.idModuloRol = idModuloRol;
    }
    public LcModuloRol(int idModuloRol, LcEmpresa lcEmpresa, LcModulos lcModulos, LcRoles lcRoles, Integer nivelModulo, Integer grupoMod, Date fechaCreacion, String estado, Integer ordenReg) {
       this.idModuloRol = idModuloRol;
       this.lcEmpresa = lcEmpresa;
       this.lcModulos = lcModulos;
       this.lcRoles = lcRoles;
       this.nivelModulo = nivelModulo;
       this.grupoMod = grupoMod;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
       this.ordenReg = ordenReg;
    }
   
    public int getIdModuloRol() {
        return this.idModuloRol;
    }
    
    public void setIdModuloRol(int idModuloRol) {
        this.idModuloRol = idModuloRol;
    }
    public LcEmpresa getLcEmpresa() {
        return this.lcEmpresa;
    }
    
    public void setLcEmpresa(LcEmpresa lcEmpresa) {
        this.lcEmpresa = lcEmpresa;
    }
    public LcModulos getLcModulos() {
        return this.lcModulos;
    }
    
    public void setLcModulos(LcModulos lcModulos) {
        this.lcModulos = lcModulos;
    }
    public LcRoles getLcRoles() {
        return this.lcRoles;
    }
    
    public void setLcRoles(LcRoles lcRoles) {
        this.lcRoles = lcRoles;
    }
    public Integer getNivelModulo() {
        return this.nivelModulo;
    }
    
    public void setNivelModulo(Integer nivelModulo) {
        this.nivelModulo = nivelModulo;
    }
    public Integer getGrupoMod() {
        return this.grupoMod;
    }
    
    public void setGrupoMod(Integer grupoMod) {
        this.grupoMod = grupoMod;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getOrdenReg() {
        return this.ordenReg;
    }
    
    public void setOrdenReg(Integer ordenReg) {
        this.ordenReg = ordenReg;
    }




}


