package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcNotificaciones generated by hbm2java
 */
public class LcNotificaciones  implements java.io.Serializable {


     private int idNotificacion;
     private String titulo;
     private String mensaje;
     private String tipoNotificacion;
     private String icono;
     private String remitente;
     private Integer receptor;
     private Date fechaCreacion;
     private Date fechaRecepcion;
     private String observacion;
     private String estado;

    public LcNotificaciones() {
    }

	
    public LcNotificaciones(int idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public LcNotificaciones(int idNotificacion, String titulo, String mensaje, String tipoNotificacion, String icono, String remitente, Integer receptor, Date fechaCreacion, Date fechaRecepcion, String observacion, String estado) {
       this.idNotificacion = idNotificacion;
       this.titulo = titulo;
       this.mensaje = mensaje;
       this.tipoNotificacion = tipoNotificacion;
       this.icono = icono;
       this.remitente = remitente;
       this.receptor = receptor;
       this.fechaCreacion = fechaCreacion;
       this.fechaRecepcion = fechaRecepcion;
       this.observacion = observacion;
       this.estado = estado;
    }
   
    public int getIdNotificacion() {
        return this.idNotificacion;
    }
    
    public void setIdNotificacion(int idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public String getTipoNotificacion() {
        return this.tipoNotificacion;
    }
    
    public void setTipoNotificacion(String tipoNotificacion) {
        this.tipoNotificacion = tipoNotificacion;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }
    public String getRemitente() {
        return this.remitente;
    }
    
    public void setRemitente(String remitente) {
        this.remitente = remitente;
    }
    public Integer getReceptor() {
        return this.receptor;
    }
    
    public void setReceptor(Integer receptor) {
        this.receptor = receptor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


