package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcNotas generated by hbm2java
 */
public class LcNotas  implements java.io.Serializable {


     private int idNota;
     private Integer idDeudor;
     private Integer idCliente;
     private String observacion;
     private Date fechaTransaccion;
     private String estado;
     private Integer idTransaccion;
     private String notaAdmin;

    public LcNotas() {
    }

	
    public LcNotas(int idNota) {
        this.idNota = idNota;
    }
    public LcNotas(int idNota, Integer idDeudor, Integer idCliente, String observacion, Date fechaTransaccion, String estado, Integer idTransaccion, String notaAdmin) {
       this.idNota = idNota;
       this.idDeudor = idDeudor;
       this.idCliente = idCliente;
       this.observacion = observacion;
       this.fechaTransaccion = fechaTransaccion;
       this.estado = estado;
       this.idTransaccion = idTransaccion;
       this.notaAdmin = notaAdmin;
    }
   
    public int getIdNota() {
        return this.idNota;
    }
    
    public void setIdNota(int idNota) {
        this.idNota = idNota;
    }
    public Integer getIdDeudor() {
        return this.idDeudor;
    }
    
    public void setIdDeudor(Integer idDeudor) {
        this.idDeudor = idDeudor;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaTransaccion() {
        return this.fechaTransaccion;
    }
    
    public void setFechaTransaccion(Date fechaTransaccion) {
        this.fechaTransaccion = fechaTransaccion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(Integer idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public String getNotaAdmin() {
        return this.notaAdmin;
    }
    
    public void setNotaAdmin(String notaAdmin) {
        this.notaAdmin = notaAdmin;
    }




}


