package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1



/**
 * LcParroquias generated by hbm2java
 */
public class LcParroquias  implements java.io.Serializable {


     private int idParriquia;
     private LcCantones lcCantones;
     private Integer idProvincia;
     private String parroquia;
     private String estado;

    public LcParroquias() {
    }

	
    public LcParroquias(int idParriquia) {
        this.idParriquia = idParriquia;
    }
    public LcParroquias(int idParriquia, LcCantones lcCantones, Integer idProvincia, String parroquia, String estado) {
       this.idParriquia = idParriquia;
       this.lcCantones = lcCantones;
       this.idProvincia = idProvincia;
       this.parroquia = parroquia;
       this.estado = estado;
    }
   
    public int getIdParriquia() {
        return this.idParriquia;
    }
    
    public void setIdParriquia(int idParriquia) {
        this.idParriquia = idParriquia;
    }
    public LcCantones getLcCantones() {
        return this.lcCantones;
    }
    
    public void setLcCantones(LcCantones lcCantones) {
        this.lcCantones = lcCantones;
    }
    public Integer getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(Integer idProvincia) {
        this.idProvincia = idProvincia;
    }
    public String getParroquia() {
        return this.parroquia;
    }
    
    public void setParroquia(String parroquia) {
        this.parroquia = parroquia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


