package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcRecordatorios generated by hbm2java
 */
public class LcRecordatorios  implements java.io.Serializable {


     private int idRecordatorio;
     private LcAgencia lcAgencia;
     private LcClientes lcClientes;
     private LcDatosDeudores lcDatosDeudores;
     private LcEmpleados lcEmpleados;
     private LcEmpresa lcEmpresa;
     private Date fechaCompromiso;
     private String revisado;
     private Date fechaRegistro;
     private Date fechaActualizado;
     private String estado;

    public LcRecordatorios() {
    }

	
    public LcRecordatorios(int idRecordatorio) {
        this.idRecordatorio = idRecordatorio;
    }
    public LcRecordatorios(int idRecordatorio, LcAgencia lcAgencia, LcClientes lcClientes, LcDatosDeudores lcDatosDeudores, LcEmpleados lcEmpleados, LcEmpresa lcEmpresa, Date fechaCompromiso, String revisado, Date fechaRegistro, Date fechaActualizado, String estado) {
       this.idRecordatorio = idRecordatorio;
       this.lcAgencia = lcAgencia;
       this.lcClientes = lcClientes;
       this.lcDatosDeudores = lcDatosDeudores;
       this.lcEmpleados = lcEmpleados;
       this.lcEmpresa = lcEmpresa;
       this.fechaCompromiso = fechaCompromiso;
       this.revisado = revisado;
       this.fechaRegistro = fechaRegistro;
       this.fechaActualizado = fechaActualizado;
       this.estado = estado;
    }
   
    public int getIdRecordatorio() {
        return this.idRecordatorio;
    }
    
    public void setIdRecordatorio(int idRecordatorio) {
        this.idRecordatorio = idRecordatorio;
    }
    public LcAgencia getLcAgencia() {
        return this.lcAgencia;
    }
    
    public void setLcAgencia(LcAgencia lcAgencia) {
        this.lcAgencia = lcAgencia;
    }
    public LcClientes getLcClientes() {
        return this.lcClientes;
    }
    
    public void setLcClientes(LcClientes lcClientes) {
        this.lcClientes = lcClientes;
    }
    public LcDatosDeudores getLcDatosDeudores() {
        return this.lcDatosDeudores;
    }
    
    public void setLcDatosDeudores(LcDatosDeudores lcDatosDeudores) {
        this.lcDatosDeudores = lcDatosDeudores;
    }
    public LcEmpleados getLcEmpleados() {
        return this.lcEmpleados;
    }
    
    public void setLcEmpleados(LcEmpleados lcEmpleados) {
        this.lcEmpleados = lcEmpleados;
    }
    public LcEmpresa getLcEmpresa() {
        return this.lcEmpresa;
    }
    
    public void setLcEmpresa(LcEmpresa lcEmpresa) {
        this.lcEmpresa = lcEmpresa;
    }
    public Date getFechaCompromiso() {
        return this.fechaCompromiso;
    }
    
    public void setFechaCompromiso(Date fechaCompromiso) {
        this.fechaCompromiso = fechaCompromiso;
    }
    public String getRevisado() {
        return this.revisado;
    }
    
    public void setRevisado(String revisado) {
        this.revisado = revisado;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaActualizado() {
        return this.fechaActualizado;
    }
    
    public void setFechaActualizado(Date fechaActualizado) {
        this.fechaActualizado = fechaActualizado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


