package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LcRecaudaciones generated by hbm2java
 */
public class LcRecaudaciones  implements java.io.Serializable {


     private int idRecaudacion;
     private LcDatosDeudores lcDatosDeudores;
     private Integer idEmpresa;
     private Integer idAgencia;
     private Integer idCliente;
     private Integer idEmpleado;
     private BigDecimal valorRecaudado;
     private Date fechaRegistro;
     private Date fechaActualizado;
     private String estado;
     private String descripcionCarga;
     private String origen;
     private Integer idTransaccion;
     private Set lcFormapagoRecaudacions = new HashSet(0);
     private Set lcDetRecaudacioneses = new HashSet(0);

    public LcRecaudaciones() {
    }

	
    public LcRecaudaciones(int idRecaudacion) {
        this.idRecaudacion = idRecaudacion;
    }
    public LcRecaudaciones(int idRecaudacion, LcDatosDeudores lcDatosDeudores, Integer idEmpresa, Integer idAgencia, Integer idCliente, Integer idEmpleado, BigDecimal valorRecaudado, Date fechaRegistro, Date fechaActualizado, String estado, String descripcionCarga, String origen, Integer idTransaccion, Set lcFormapagoRecaudacions, Set lcDetRecaudacioneses) {
       this.idRecaudacion = idRecaudacion;
       this.lcDatosDeudores = lcDatosDeudores;
       this.idEmpresa = idEmpresa;
       this.idAgencia = idAgencia;
       this.idCliente = idCliente;
       this.idEmpleado = idEmpleado;
       this.valorRecaudado = valorRecaudado;
       this.fechaRegistro = fechaRegistro;
       this.fechaActualizado = fechaActualizado;
       this.estado = estado;
       this.descripcionCarga = descripcionCarga;
       this.origen = origen;
       this.idTransaccion = idTransaccion;
       this.lcFormapagoRecaudacions = lcFormapagoRecaudacions;
       this.lcDetRecaudacioneses = lcDetRecaudacioneses;
    }
   
    public int getIdRecaudacion() {
        return this.idRecaudacion;
    }
    
    public void setIdRecaudacion(int idRecaudacion) {
        this.idRecaudacion = idRecaudacion;
    }
    public LcDatosDeudores getLcDatosDeudores() {
        return this.lcDatosDeudores;
    }
    
    public void setLcDatosDeudores(LcDatosDeudores lcDatosDeudores) {
        this.lcDatosDeudores = lcDatosDeudores;
    }
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Integer getIdAgencia() {
        return this.idAgencia;
    }
    
    public void setIdAgencia(Integer idAgencia) {
        this.idAgencia = idAgencia;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public BigDecimal getValorRecaudado() {
        return this.valorRecaudado;
    }
    
    public void setValorRecaudado(BigDecimal valorRecaudado) {
        this.valorRecaudado = valorRecaudado;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaActualizado() {
        return this.fechaActualizado;
    }
    
    public void setFechaActualizado(Date fechaActualizado) {
        this.fechaActualizado = fechaActualizado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getDescripcionCarga() {
        return this.descripcionCarga;
    }
    
    public void setDescripcionCarga(String descripcionCarga) {
        this.descripcionCarga = descripcionCarga;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public Integer getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(Integer idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public Set getLcFormapagoRecaudacions() {
        return this.lcFormapagoRecaudacions;
    }
    
    public void setLcFormapagoRecaudacions(Set lcFormapagoRecaudacions) {
        this.lcFormapagoRecaudacions = lcFormapagoRecaudacions;
    }
    public Set getLcDetRecaudacioneses() {
        return this.lcDetRecaudacioneses;
    }
    
    public void setLcDetRecaudacioneses(Set lcDetRecaudacioneses) {
        this.lcDetRecaudacioneses = lcDetRecaudacioneses;
    }




}


