package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LcSegmento generated by hbm2java
 */
public class LcSegmento  implements java.io.Serializable {


     private int idSegmento;
     private LcSubcartera lcSubcartera;
     private String nombreSegmento;
     private Date fechaCreacion;
     private String estado;
     private Set lcSubsegmentos = new HashSet(0);

    public LcSegmento() {
    }

	
    public LcSegmento(int idSegmento) {
        this.idSegmento = idSegmento;
    }
    public LcSegmento(int idSegmento, LcSubcartera lcSubcartera, String nombreSegmento, Date fechaCreacion, String estado, Set lcSubsegmentos) {
       this.idSegmento = idSegmento;
       this.lcSubcartera = lcSubcartera;
       this.nombreSegmento = nombreSegmento;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
       this.lcSubsegmentos = lcSubsegmentos;
    }
   
    public int getIdSegmento() {
        return this.idSegmento;
    }
    
    public void setIdSegmento(int idSegmento) {
        this.idSegmento = idSegmento;
    }
    public LcSubcartera getLcSubcartera() {
        return this.lcSubcartera;
    }
    
    public void setLcSubcartera(LcSubcartera lcSubcartera) {
        this.lcSubcartera = lcSubcartera;
    }
    public String getNombreSegmento() {
        return this.nombreSegmento;
    }
    
    public void setNombreSegmento(String nombreSegmento) {
        this.nombreSegmento = nombreSegmento;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getLcSubsegmentos() {
        return this.lcSubsegmentos;
    }
    
    public void setLcSubsegmentos(Set lcSubsegmentos) {
        this.lcSubsegmentos = lcSubsegmentos;
    }




}


