package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LcTiposDireccion generated by hbm2java
 */
public class LcTiposDireccion  implements java.io.Serializable {


     private int idTipoDir;
     private String nombreTipoDireccion;
     private String observacion;
     private Date fechaCreacion;
     private String estado;
     private Set lcDireccions = new HashSet(0);

    public LcTiposDireccion() {
    }

	
    public LcTiposDireccion(int idTipoDir) {
        this.idTipoDir = idTipoDir;
    }
    public LcTiposDireccion(int idTipoDir, String nombreTipoDireccion, String observacion, Date fechaCreacion, String estado, Set lcDireccions) {
       this.idTipoDir = idTipoDir;
       this.nombreTipoDireccion = nombreTipoDireccion;
       this.observacion = observacion;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
       this.lcDireccions = lcDireccions;
    }
   
    public int getIdTipoDir() {
        return this.idTipoDir;
    }
    
    public void setIdTipoDir(int idTipoDir) {
        this.idTipoDir = idTipoDir;
    }
    public String getNombreTipoDireccion() {
        return this.nombreTipoDireccion;
    }
    
    public void setNombreTipoDireccion(String nombreTipoDireccion) {
        this.nombreTipoDireccion = nombreTipoDireccion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getLcDireccions() {
        return this.lcDireccions;
    }
    
    public void setLcDireccions(Set lcDireccions) {
        this.lcDireccions = lcDireccions;
    }




}


