package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LcTipoGestion generated by hbm2java
 */
public class LcTipoGestion  implements java.io.Serializable {


     private int idTipoGestion;
     private String nombreTipoGestion;
     private Integer idCliente;
     private String observacion;
     private Date fechaRegistro;
     private String estado;
     private Set lcGestioneses = new HashSet(0);

    public LcTipoGestion() {
    }

	
    public LcTipoGestion(int idTipoGestion) {
        this.idTipoGestion = idTipoGestion;
    }
    public LcTipoGestion(int idTipoGestion, String nombreTipoGestion, Integer idCliente, String observacion, Date fechaRegistro, String estado, Set lcGestioneses) {
       this.idTipoGestion = idTipoGestion;
       this.nombreTipoGestion = nombreTipoGestion;
       this.idCliente = idCliente;
       this.observacion = observacion;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
       this.lcGestioneses = lcGestioneses;
    }
   
    public int getIdTipoGestion() {
        return this.idTipoGestion;
    }
    
    public void setIdTipoGestion(int idTipoGestion) {
        this.idTipoGestion = idTipoGestion;
    }
    public String getNombreTipoGestion() {
        return this.nombreTipoGestion;
    }
    
    public void setNombreTipoGestion(String nombreTipoGestion) {
        this.nombreTipoGestion = nombreTipoGestion;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getLcGestioneses() {
        return this.lcGestioneses;
    }
    
    public void setLcGestioneses(Set lcGestioneses) {
        this.lcGestioneses = lcGestioneses;
    }




}


