package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LcTipoResultado generated by hbm2java
 */
public class LcTipoResultado  implements java.io.Serializable {


     private int idTipoResultado;
     private Integer idTipoGestion;
     private String nombreTipoResultado;
     private String observacion;
     private Date fechaRegistro;
     private String estado;
     private Set lcClienteResultados = new HashSet(0);
     private Set lcGestioneses = new HashSet(0);

    public LcTipoResultado() {
    }

	
    public LcTipoResultado(int idTipoResultado) {
        this.idTipoResultado = idTipoResultado;
    }
    public LcTipoResultado(int idTipoResultado, Integer idTipoGestion, String nombreTipoResultado, String observacion, Date fechaRegistro, String estado, Set lcClienteResultados, Set lcGestioneses) {
       this.idTipoResultado = idTipoResultado;
       this.idTipoGestion = idTipoGestion;
       this.nombreTipoResultado = nombreTipoResultado;
       this.observacion = observacion;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
       this.lcClienteResultados = lcClienteResultados;
       this.lcGestioneses = lcGestioneses;
    }
   
    public int getIdTipoResultado() {
        return this.idTipoResultado;
    }
    
    public void setIdTipoResultado(int idTipoResultado) {
        this.idTipoResultado = idTipoResultado;
    }
    public Integer getIdTipoGestion() {
        return this.idTipoGestion;
    }
    
    public void setIdTipoGestion(Integer idTipoGestion) {
        this.idTipoGestion = idTipoGestion;
    }
    public String getNombreTipoResultado() {
        return this.nombreTipoResultado;
    }
    
    public void setNombreTipoResultado(String nombreTipoResultado) {
        this.nombreTipoResultado = nombreTipoResultado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getLcClienteResultados() {
        return this.lcClienteResultados;
    }
    
    public void setLcClienteResultados(Set lcClienteResultados) {
        this.lcClienteResultados = lcClienteResultados;
    }
    public Set getLcGestioneses() {
        return this.lcGestioneses;
    }
    
    public void setLcGestioneses(Set lcGestioneses) {
        this.lcGestioneses = lcGestioneses;
    }




}


