package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LcTipoCredito generated by hbm2java
 */
public class LcTipoCredito  implements java.io.Serializable {


     private int idTipocredito;
     private String descripcion;
     private Date fechaCreacion;
     private String estado;
     private Set lcDatosDeudoreses = new HashSet(0);

    public LcTipoCredito() {
    }

	
    public LcTipoCredito(int idTipocredito) {
        this.idTipocredito = idTipocredito;
    }
    public LcTipoCredito(int idTipocredito, String descripcion, Date fechaCreacion, String estado, Set lcDatosDeudoreses) {
       this.idTipocredito = idTipocredito;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
       this.lcDatosDeudoreses = lcDatosDeudoreses;
    }
   
    public int getIdTipocredito() {
        return this.idTipocredito;
    }
    
    public void setIdTipocredito(int idTipocredito) {
        this.idTipocredito = idTipocredito;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getLcDatosDeudoreses() {
        return this.lcDatosDeudoreses;
    }
    
    public void setLcDatosDeudoreses(Set lcDatosDeudoreses) {
        this.lcDatosDeudoreses = lcDatosDeudoreses;
    }




}


