package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcTiposEstatus generated by hbm2java
 */
public class LcTiposEstatus  implements java.io.Serializable {


     private int idEstatus;
     private Integer idEmpresa;
     private String descripcion;
     private Date fechaCreacion;
     private String estado;

    public LcTiposEstatus() {
    }

	
    public LcTiposEstatus(int idEstatus) {
        this.idEstatus = idEstatus;
    }
    public LcTiposEstatus(int idEstatus, Integer idEmpresa, String descripcion, Date fechaCreacion, String estado) {
       this.idEstatus = idEstatus;
       this.idEmpresa = idEmpresa;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
    }
   
    public int getIdEstatus() {
        return this.idEstatus;
    }
    
    public void setIdEstatus(int idEstatus) {
        this.idEstatus = idEstatus;
    }
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


