package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LcTipoReferencia generated by hbm2java
 */
public class LcTipoReferencia  implements java.io.Serializable {


     private int idTipoRef;
     private String nombreTipo;
     private String descripcion;
     private Date fechaCreacion;
     private String estado;
     private Set lcReferenciases = new HashSet(0);

    public LcTipoReferencia() {
    }

	
    public LcTipoReferencia(int idTipoRef) {
        this.idTipoRef = idTipoRef;
    }
    public LcTipoReferencia(int idTipoRef, String nombreTipo, String descripcion, Date fechaCreacion, String estado, Set lcReferenciases) {
       this.idTipoRef = idTipoRef;
       this.nombreTipo = nombreTipo;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
       this.lcReferenciases = lcReferenciases;
    }
   
    public int getIdTipoRef() {
        return this.idTipoRef;
    }
    
    public void setIdTipoRef(int idTipoRef) {
        this.idTipoRef = idTipoRef;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getLcReferenciases() {
        return this.lcReferenciases;
    }
    
    public void setLcReferenciases(Set lcReferenciases) {
        this.lcReferenciases = lcReferenciases;
    }




}


