package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1



/**
 * MisNombres generated by hbm2java
 */
public class MisNombres  implements java.io.Serializable {


     private MisNombresId id;

    public MisNombres() {
    }

    public MisNombres(MisNombresId id) {
       this.id = id;
    }
   
    public MisNombresId getId() {
        return this.id;
    }
    
    public void setId(MisNombresId id) {
        this.id = id;
    }




}


