package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1



/**
 * MisNombresId generated by hbm2java
 */
public class MisNombresId  implements java.io.Serializable {


     private String identificacion;
     private String nombresCompleto;

    public MisNombresId() {
    }

    public MisNombresId(String identificacion, String nombresCompleto) {
       this.identificacion = identificacion;
       this.nombresCompleto = nombresCompleto;
    }
   
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public String getNombresCompleto() {
        return this.nombresCompleto;
    }
    
    public void setNombresCompleto(String nombresCompleto) {
        this.nombresCompleto = nombresCompleto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MisNombresId) ) return false;
		 MisNombresId castOther = ( MisNombresId ) other; 
         
		 return ( (this.getIdentificacion()==castOther.getIdentificacion()) || ( this.getIdentificacion()!=null && castOther.getIdentificacion()!=null && this.getIdentificacion().equals(castOther.getIdentificacion()) ) )
 && ( (this.getNombresCompleto()==castOther.getNombresCompleto()) || ( this.getNombresCompleto()!=null && castOther.getNombresCompleto()!=null && this.getNombresCompleto().equals(castOther.getNombresCompleto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdentificacion() == null ? 0 : this.getIdentificacion().hashCode() );
         result = 37 * result + ( getNombresCompleto() == null ? 0 : this.getNombresCompleto().hashCode() );
         return result;
   }   


}


