package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1



/**
 * SeqCartera generated by hbm2java
 */
public class SeqCartera  implements java.io.Serializable {


     private SeqCarteraId id;

    public SeqCartera() {
    }

    public SeqCartera(SeqCarteraId id) {
       this.id = id;
    }
   
    public SeqCarteraId getId() {
        return this.id;
    }
    
    public void setId(SeqCarteraId id) {
        this.id = id;
    }




}


