package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1



/**
 * VwConsultaCarteraEmpleados generated by hbm2java
 */
public class VwConsultaCarteraEmpleados  implements java.io.Serializable {


     private VwConsultaCarteraEmpleadosId id;

    public VwConsultaCarteraEmpleados() {
    }

    public VwConsultaCarteraEmpleados(VwConsultaCarteraEmpleadosId id) {
       this.id = id;
    }
   
    public VwConsultaCarteraEmpleadosId getId() {
        return this.id;
    }
    
    public void setId(VwConsultaCarteraEmpleadosId id) {
        this.id = id;
    }




}


