package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1



/**
 * VwConsultaClientes generated by hbm2java
 */
public class VwConsultaClientes  implements java.io.Serializable {


     private VwConsultaClientesId id;

    public VwConsultaClientes() {
    }

    public VwConsultaClientes(VwConsultaClientesId id) {
       this.id = id;
    }
   
    public VwConsultaClientesId getId() {
        return this.id;
    }
    
    public void setId(VwConsultaClientesId id) {
        this.id = id;
    }




}


