package com.siscogescorp.modelo;
// Generated 24/05/2018 12:17:21 by Hibernate Tools 4.3.1



/**
 * VwConsultaCarteraAsignacion generated by hbm2java
 */
public class VwConsultaCarteraAsignacion  implements java.io.Serializable {


     private VwConsultaCarteraAsignacionId id;

    public VwConsultaCarteraAsignacion() {
    }

    public VwConsultaCarteraAsignacion(VwConsultaCarteraAsignacionId id) {
       this.id = id;
    }
   
    public VwConsultaCarteraAsignacionId getId() {
        return this.id;
    }
    
    public void setId(VwConsultaCarteraAsignacionId id) {
        this.id = id;
    }




}


