package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VwConsultaCuadreCajaId generated by hbm2java
 */
public class VwConsultaCuadreCajaId  implements java.io.Serializable {


     private Integer idRecaudacion;
     private String tformaPagos;
     private String cedente;
     private String cliente;
     private Date fechaRegistro;
     private BigDecimal valorRecaudado;

    public VwConsultaCuadreCajaId() {
    }

    public VwConsultaCuadreCajaId(Integer idRecaudacion, String tformaPagos, String cedente, String cliente, Date fechaRegistro, BigDecimal valorRecaudado) {
       this.idRecaudacion = idRecaudacion;
       this.tformaPagos = tformaPagos;
       this.cedente = cedente;
       this.cliente = cliente;
       this.fechaRegistro = fechaRegistro;
       this.valorRecaudado = valorRecaudado;
    }
   
    public Integer getIdRecaudacion() {
        return this.idRecaudacion;
    }
    
    public void setIdRecaudacion(Integer idRecaudacion) {
        this.idRecaudacion = idRecaudacion;
    }
    public String getTformaPagos() {
        return this.tformaPagos;
    }
    
    public void setTformaPagos(String tformaPagos) {
        this.tformaPagos = tformaPagos;
    }
    public String getCedente() {
        return this.cedente;
    }
    
    public void setCedente(String cedente) {
        this.cedente = cedente;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public BigDecimal getValorRecaudado() {
        return this.valorRecaudado;
    }
    
    public void setValorRecaudado(BigDecimal valorRecaudado) {
        this.valorRecaudado = valorRecaudado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VwConsultaCuadreCajaId) ) return false;
		 VwConsultaCuadreCajaId castOther = ( VwConsultaCuadreCajaId ) other; 
         
		 return ( (this.getIdRecaudacion()==castOther.getIdRecaudacion()) || ( this.getIdRecaudacion()!=null && castOther.getIdRecaudacion()!=null && this.getIdRecaudacion().equals(castOther.getIdRecaudacion()) ) )
 && ( (this.getTformaPagos()==castOther.getTformaPagos()) || ( this.getTformaPagos()!=null && castOther.getTformaPagos()!=null && this.getTformaPagos().equals(castOther.getTformaPagos()) ) )
 && ( (this.getCedente()==castOther.getCedente()) || ( this.getCedente()!=null && castOther.getCedente()!=null && this.getCedente().equals(castOther.getCedente()) ) )
 && ( (this.getCliente()==castOther.getCliente()) || ( this.getCliente()!=null && castOther.getCliente()!=null && this.getCliente().equals(castOther.getCliente()) ) )
 && ( (this.getFechaRegistro()==castOther.getFechaRegistro()) || ( this.getFechaRegistro()!=null && castOther.getFechaRegistro()!=null && this.getFechaRegistro().equals(castOther.getFechaRegistro()) ) )
 && ( (this.getValorRecaudado()==castOther.getValorRecaudado()) || ( this.getValorRecaudado()!=null && castOther.getValorRecaudado()!=null && this.getValorRecaudado().equals(castOther.getValorRecaudado()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdRecaudacion() == null ? 0 : this.getIdRecaudacion().hashCode() );
         result = 37 * result + ( getTformaPagos() == null ? 0 : this.getTformaPagos().hashCode() );
         result = 37 * result + ( getCedente() == null ? 0 : this.getCedente().hashCode() );
         result = 37 * result + ( getCliente() == null ? 0 : this.getCliente().hashCode() );
         result = 37 * result + ( getFechaRegistro() == null ? 0 : this.getFechaRegistro().hashCode() );
         result = 37 * result + ( getValorRecaudado() == null ? 0 : this.getValorRecaudado().hashCode() );
         return result;
   }   


}


