package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1



/**
 * VwConsultaGestionesId generated by hbm2java
 */
public class VwConsultaGestionesId  implements java.io.Serializable {


     private Double mes;
     private String mest;
     private String usuario;
     private Integer idEmpleado;
     private Long cantidad;

    public VwConsultaGestionesId() {
    }

    public VwConsultaGestionesId(Double mes, String mest, String usuario, Integer idEmpleado, Long cantidad) {
       this.mes = mes;
       this.mest = mest;
       this.usuario = usuario;
       this.idEmpleado = idEmpleado;
       this.cantidad = cantidad;
    }
   
    public Double getMes() {
        return this.mes;
    }
    
    public void setMes(Double mes) {
        this.mes = mes;
    }
    public String getMest() {
        return this.mest;
    }
    
    public void setMest(String mest) {
        this.mest = mest;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Long getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Long cantidad) {
        this.cantidad = cantidad;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VwConsultaGestionesId) ) return false;
		 VwConsultaGestionesId castOther = ( VwConsultaGestionesId ) other; 
         
		 return ( (this.getMes()==castOther.getMes()) || ( this.getMes()!=null && castOther.getMes()!=null && this.getMes().equals(castOther.getMes()) ) )
 && ( (this.getMest()==castOther.getMest()) || ( this.getMest()!=null && castOther.getMest()!=null && this.getMest().equals(castOther.getMest()) ) )
 && ( (this.getUsuario()==castOther.getUsuario()) || ( this.getUsuario()!=null && castOther.getUsuario()!=null && this.getUsuario().equals(castOther.getUsuario()) ) )
 && ( (this.getIdEmpleado()==castOther.getIdEmpleado()) || ( this.getIdEmpleado()!=null && castOther.getIdEmpleado()!=null && this.getIdEmpleado().equals(castOther.getIdEmpleado()) ) )
 && ( (this.getCantidad()==castOther.getCantidad()) || ( this.getCantidad()!=null && castOther.getCantidad()!=null && this.getCantidad().equals(castOther.getCantidad()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMes() == null ? 0 : this.getMes().hashCode() );
         result = 37 * result + ( getMest() == null ? 0 : this.getMest().hashCode() );
         result = 37 * result + ( getUsuario() == null ? 0 : this.getUsuario().hashCode() );
         result = 37 * result + ( getIdEmpleado() == null ? 0 : this.getIdEmpleado().hashCode() );
         result = 37 * result + ( getCantidad() == null ? 0 : this.getCantidad().hashCode() );
         return result;
   }   


}


