package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1



/**
 * VwConsultaGestiones generated by hbm2java
 */
public class VwConsultaGestiones  implements java.io.Serializable {


     private VwConsultaGestionesId id;

    public VwConsultaGestiones() {
    }

    public VwConsultaGestiones(VwConsultaGestionesId id) {
       this.id = id;
    }
   
    public VwConsultaGestionesId getId() {
        return this.id;
    }
    
    public void setId(VwConsultaGestionesId id) {
        this.id = id;
    }




}


