package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1



/**
 * VwConsultaCartera33 generated by hbm2java
 */
public class VwConsultaCartera33  implements java.io.Serializable {


     private VwConsultaCartera33Id id;

    public VwConsultaCartera33() {
    }

    public VwConsultaCartera33(VwConsultaCartera33Id id) {
       this.id = id;
    }
   
    public VwConsultaCartera33Id getId() {
        return this.id;
    }
    
    public void setId(VwConsultaCartera33Id id) {
        this.id = id;
    }




}


