package com.siscogescorp.modelo;
// Generated 14-ene-2018 19:02:18 by Hibernate Tools 4.3.1



/**
 * VwConsultaCuadreCaja generated by hbm2java
 */
public class VwConsultaCuadreCaja  implements java.io.Serializable {


     private VwConsultaCuadreCajaId id;

    public VwConsultaCuadreCaja() {
    }

    public VwConsultaCuadreCaja(VwConsultaCuadreCajaId id) {
       this.id = id;
    }
   
    public VwConsultaCuadreCajaId getId() {
        return this.id;
    }
    
    public void setId(VwConsultaCuadreCajaId id) {
        this.id = id;
    }




}


